version: '3.8'
services:

  postgres-service:
    container_name: postgres-service
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

