apiVersion: v1
kind: Service
metadata:
  name: spring-argocd-app
spec:
  selector:
    app: spring-argocd-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-argocd-app
spec:
  selector:
    matchLabels:
      app: spring-argocd-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-argocd-app
    spec:
      containers:
        - name: spring-argocd-app
          image: mertcakmak2/spring-argocd-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080